apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:\k8s_userdata
    type: DirectoryOrCreate